version: '3.9'

services:
  activemq:
    image: webcenter/activemq
    container_name: activemq
    environment:
      - 'TZ=Europe/Amsterdam'
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 61616:61616 #JMS
      - 8161:8161   #UI